package com.hrms.enums;
public enum CandidateStage {
    APPLIED, SCREENING, INTERVIEW_ROUND_1, INTERVIEW_ROUND_2,
    TECHNICAL, HR_ROUND, OFFER_PENDING, OFFER_ACCEPTED, OFFER_REJECTED, HIRED, DROPPED
}
