package com.hrms.enums;
public enum NotificationType {
    LEAVE_APPLIED, LEAVE_APPROVED, LEAVE_REJECTED,
    PAYROLL_PROCESSED, INTERVIEW_SCHEDULED, OFFER_ISSUED,
    TASK_ASSIGNED, REVIEW_DUE, ACCOUNT_LOCKED,
    BIRTHDAY, WORK_ANNIVERSARY, ANNOUNCEMENT, SYSTEM
}
